// bdnull -- boundary-decoder NEGATIVE control, generated by
// gen_bdec_fixture.py.  Same size, same density, same emitter as
// bdwin, but the rows are independent: the smallest pairwise row
// difference is 10, so no single row addition can pay for
// itself and --bdec should decline.
// Direct realisation: 54 XOR2.
module bdnull(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, y0, y1, y2, y3, y4, y5);
  input x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23;
  output y0, y1, y2, y3, y4, y5;
  wire w0_1, w0_2, w0_3, w0_4, w0_5, w0_6, w0_7, w0_8, w1_1, w1_2, w1_3, w1_4, w1_5, w1_6, w1_7, w1_8, w2_1, w2_2, w2_3, w2_4, w2_5, w2_6, w2_7, w2_8, w3_1, w3_2, w3_3, w3_4, w3_5, w3_6, w3_7, w3_8, w4_1, w4_2, w4_3, w4_4, w4_5, w4_6, w4_7, w4_8, w5_1, w5_2, w5_3, w5_4, w5_5, w5_6, w5_7, w5_8;
  xor g0(w0_1, x0, x4);
  xor g1(w0_2, x9, x10);
  xor g2(w0_3, x11, x12);
  xor g3(w0_4, x14, x15);
  xor g4(w0_5, x18, x21);
  xor g5(w0_6, w0_1, w0_2);
  xor g6(w0_7, w0_3, w0_4);
  xor g7(w0_8, w0_6, w0_7);
  xor g8(y0, w0_8, w0_5);
  xor g9(w1_1, x0, x1);
  xor g10(w1_2, x2, x5);
  xor g11(w1_3, x6, x8);
  xor g12(w1_4, x9, x10);
  xor g13(w1_5, x17, x20);
  xor g14(w1_6, w1_1, w1_2);
  xor g15(w1_7, w1_3, w1_4);
  xor g16(w1_8, w1_6, w1_7);
  xor g17(y1, w1_8, w1_5);
  xor g18(w2_1, x3, x6);
  xor g19(w2_2, x9, x10);
  xor g20(w2_3, x11, x12);
  xor g21(w2_4, x13, x16);
  xor g22(w2_5, x18, x19);
  xor g23(w2_6, w2_1, w2_2);
  xor g24(w2_7, w2_3, w2_4);
  xor g25(w2_8, w2_6, w2_7);
  xor g26(y2, w2_8, w2_5);
  xor g27(w3_1, x0, x1);
  xor g28(w3_2, x2, x7);
  xor g29(w3_3, x11, x14);
  xor g30(w3_4, x17, x19);
  xor g31(w3_5, x20, x21);
  xor g32(w3_6, w3_1, w3_2);
  xor g33(w3_7, w3_3, w3_4);
  xor g34(w3_8, w3_6, w3_7);
  xor g35(y3, w3_8, w3_5);
  xor g36(w4_1, x1, x2);
  xor g37(w4_2, x3, x4);
  xor g38(w4_3, x6, x12);
  xor g39(w4_4, x15, x21);
  xor g40(w4_5, x22, x23);
  xor g41(w4_6, w4_1, w4_2);
  xor g42(w4_7, w4_3, w4_4);
  xor g43(w4_8, w4_6, w4_7);
  xor g44(y4, w4_8, w4_5);
  xor g45(w5_1, x1, x6);
  xor g46(w5_2, x7, x11);
  xor g47(w5_3, x14, x15);
  xor g48(w5_4, x16, x17);
  xor g49(w5_5, x22, x23);
  xor g50(w5_6, w5_1, w5_2);
  xor g51(w5_7, w5_3, w5_4);
  xor g52(w5_8, w5_6, w5_7);
  xor g53(y5, w5_8, w5_5);
endmodule
