// bdwin -- boundary-decoder POSITIVE fixture, generated by
// gen_bdec_fixture.py.  A = B^-1 H with B = I + sum_{i>=1} E_{i,0},
// an involution, so B and B^-1 both have max row weight 2.
// m=6 outputs, n=24 inputs, shared row weight 10.
// Direct realisation: 64 XOR2.  Via the re-encoding:
// 19 XOR2 (14 core + 5 decoder).
// Each output is an independent balanced tree: nothing to hash-cons.
module bdwin(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, y0, y1, y2, y3, y4, y5);
  input x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23;
  output y0, y1, y2, y3, y4, y5;
  wire w0_1, w0_2, w0_3, w0_4, w0_5, w0_6, w0_7, w0_8, w1_1, w1_2, w1_3, w1_4, w1_5, w1_6, w1_7, w1_8, w1_9, w1_10, w2_1, w2_2, w2_3, w2_4, w2_5, w2_6, w2_7, w2_8, w2_9, w2_10, w3_1, w3_2, w3_3, w3_4, w3_5, w3_6, w3_7, w3_8, w3_9, w3_10, w4_1, w4_2, w4_3, w4_4, w4_5, w4_6, w4_7, w4_8, w4_9, w4_10, w5_1, w5_2, w5_3, w5_4, w5_5, w5_6, w5_7, w5_8, w5_9, w5_10;
  xor g0(w0_1, x0, x1);
  xor g1(w0_2, x2, x3);
  xor g2(w0_3, x4, x7);
  xor g3(w0_4, x8, x10);
  xor g4(w0_5, x11, x12);
  xor g5(w0_6, w0_1, w0_2);
  xor g6(w0_7, w0_3, w0_4);
  xor g7(w0_8, w0_6, w0_7);
  xor g8(y0, w0_8, w0_5);
  xor g9(w1_1, x0, x1);
  xor g10(w1_2, x2, x3);
  xor g11(w1_3, x4, x7);
  xor g12(w1_4, x8, x10);
  xor g13(w1_5, x11, x12);
  xor g14(w1_6, x14, x15);
  xor g15(w1_7, w1_1, w1_2);
  xor g16(w1_8, w1_3, w1_4);
  xor g17(w1_9, w1_5, w1_6);
  xor g18(w1_10, w1_7, w1_8);
  xor g19(y1, w1_10, w1_9);
  xor g20(w2_1, x0, x1);
  xor g21(w2_2, x2, x3);
  xor g22(w2_3, x4, x7);
  xor g23(w2_4, x8, x10);
  xor g24(w2_5, x11, x12);
  xor g25(w2_6, x16, x17);
  xor g26(w2_7, w2_1, w2_2);
  xor g27(w2_8, w2_3, w2_4);
  xor g28(w2_9, w2_5, w2_6);
  xor g29(w2_10, w2_7, w2_8);
  xor g30(y2, w2_10, w2_9);
  xor g31(w3_1, x0, x1);
  xor g32(w3_2, x2, x3);
  xor g33(w3_3, x4, x7);
  xor g34(w3_4, x8, x10);
  xor g35(w3_5, x11, x12);
  xor g36(w3_6, x18, x19);
  xor g37(w3_7, w3_1, w3_2);
  xor g38(w3_8, w3_3, w3_4);
  xor g39(w3_9, w3_5, w3_6);
  xor g40(w3_10, w3_7, w3_8);
  xor g41(y3, w3_10, w3_9);
  xor g42(w4_1, x0, x1);
  xor g43(w4_2, x2, x3);
  xor g44(w4_3, x4, x7);
  xor g45(w4_4, x8, x10);
  xor g46(w4_5, x11, x12);
  xor g47(w4_6, x20, x21);
  xor g48(w4_7, w4_1, w4_2);
  xor g49(w4_8, w4_3, w4_4);
  xor g50(w4_9, w4_5, w4_6);
  xor g51(w4_10, w4_7, w4_8);
  xor g52(y4, w4_10, w4_9);
  xor g53(w5_1, x0, x1);
  xor g54(w5_2, x2, x3);
  xor g55(w5_3, x4, x7);
  xor g56(w5_4, x8, x10);
  xor g57(w5_5, x11, x12);
  xor g58(w5_6, x22, x23);
  xor g59(w5_7, w5_1, w5_2);
  xor g60(w5_8, w5_3, w5_4);
  xor g61(w5_9, w5_5, w5_6);
  xor g62(w5_10, w5_7, w5_8);
  xor g63(y5, w5_10, w5_9);
endmodule
