#!/usr/bin/env python3
"""Generate GF(2) linear circuits with a KNOWN boundary-decoder optimum.

The construction starts from the answer.  Pick a sparse core H and an
invertible B, and publish A = B^{-1} H.  Then the shipped netlist realises A
directly, which is expensive, and the only cheap realisation is to recover
B -- which is exactly what --bdec searches for.

Two circuits are emitted:

  bdwin   the positive case.  Every output shares one wide common row R, and
          differs from y_0 by a distinct DISJOINT PAIR.  So the pairwise row
          differences are weight 2 while the rows themselves are weight ~24.
          B = I + sum_{i>=1} E_{i,0} is an involution, so B and B^{-1} both
          have max row weight 2, well inside the shipped bdec_wmax of 8, and
          the optimum is reachable in m-1 single row additions each of which
          pays for itself on its own.  Hill climbing should walk straight in.

  bdnull  the negative control.  Same size, same density, same emitter, but
          the rows are drawn independently, so no pair of rows has a sparse
          difference and no row addition helps.  --bdec should DECLINE.

Each output is emitted as its own balanced XOR tree over its own support,
with net names unique to that output, so no two outputs share a textual
subexpression.  A structural hasher has nothing to merge; the win is
algebraic or it does not exist.
"""
import argparse, random, os


def tree(bits, out, wname, gname, lines, gctr):
    """Emit a balanced XOR tree over `bits`, driving `out`.  Returns wires."""
    cur = list(bits)
    wires = []
    k = 0
    while len(cur) > 1:
        nxt = []
        for i in range(0, len(cur) - 1, 2):
            k += 1
            last = (len(cur) - i <= 2) and (len(cur) - (i + 2) == 0)
            dst = out if (last and len(cur) == 2) else f"{wname}_{k}"
            if dst != out:
                wires.append(dst)
            lines.append(f"  xor {gname}{gctr[0]}({dst}, {cur[i]}, {cur[i+1]});")
            gctr[0] += 1
            nxt.append(dst)
        if len(cur) % 2:
            nxt.append(cur[-1])
        cur = nxt
    if len(cur) == 1 and cur[0] != out:
        lines.append(f"  buf {gname}{gctr[0]}({out}, {cur[0]});")
        gctr[0] += 1
    return wires


def emit(name, rows, n, path, header):
    m = len(rows)
    lines, wires, gctr = [], [], [0]
    for i, r in enumerate(rows):
        bits = [f"x{j}" for j in sorted(r)]
        wires += tree(bits, f"y{i}", f"w{i}", "g", lines, gctr)
    ins = ", ".join(f"x{j}" for j in range(n))
    outs = ", ".join(f"y{i}" for i in range(m))
    body = [f"// {h}" for h in header]
    body.append(f"module {name}({ins}, {outs});")
    body.append(f"  input {ins};")
    body.append(f"  output {outs};")
    if wires:
        body.append("  wire " + ", ".join(wires) + ";")
    body += lines
    body.append("endmodule")
    open(path, "w").write("\n".join(body) + "\n")
    return gctr[0]


def cost_direct(rows):
    """XOR2 gates to realise each row independently."""
    return sum(len(r) - 1 for r in rows)


def cost_via(core, dec_weights):
    """XOR2 for the re-encoded core plus the boundary decoder."""
    return sum(max(0, len(c) - 1) for c in core) + \
           sum(w - 1 for w in dec_weights if w >= 2)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=".")
    ap.add_argument("--m", type=int, default=8, help="outputs")
    ap.add_argument("--n", type=int, default=48, help="inputs")
    ap.add_argument("--wide", type=int, default=24, help="weight of the shared row R")
    ap.add_argument("--seed", type=int, default=20260815)
    a = ap.parse_args()

    rnd = random.Random(a.seed)
    pool = list(range(a.n))

    # ---------------- positive case -------------------------------------
    # R is a wide row over the first n-2(m-1) inputs; the differences are
    # disjoint pairs drawn from the reserved tail, so they cannot collide
    # with R or with each other.
    reserved = 2 * (a.m - 1)
    body_pool = pool[:a.n - reserved]
    tail = pool[a.n - reserved:]
    R = set(rnd.sample(body_pool, a.wide))
    rows = [set(R)]
    diffs = []
    for i in range(a.m - 1):
        d = {tail[2 * i], tail[2 * i + 1]}
        diffs.append(d)
        rows.append(R ^ d)                      # symmetric difference = R + d

    core = [R] + diffs                          # h_0 = R, h_i = d_i
    dec_w = [1] + [2] * (a.m - 1)               # y_0 = h_0 ; y_i = h_0 + h_i
    d_cost = cost_direct(rows)
    v_cost = cost_via(core, dec_w)
    g = emit("bdwin", rows, a.n, os.path.join(a.out, "bdwin.v"), [
        "bdwin -- boundary-decoder POSITIVE fixture, generated by",
        "gen_bdec_fixture.py.  A = B^-1 H with B = I + sum_{i>=1} E_{i,0},",
        "an involution, so B and B^-1 both have max row weight 2.",
        f"m={a.m} outputs, n={a.n} inputs, shared row weight {a.wide}.",
        f"Direct realisation: {d_cost} XOR2.  Via the re-encoding:",
        f"{v_cost} XOR2 ({sum(len(c)-1 for c in core)} core + "
        f"{sum(w-1 for w in dec_w if w>=2)} decoder).",
        "Each output is an independent balanced tree: nothing to hash-cons.",
    ])
    print(f"bdwin.v   m={a.m} n={a.n}  emitted {g} gates")
    print(f"          row weights: {sorted(len(r) for r in rows)}")
    print(f"          direct  {d_cost} XOR2")
    print(f"          re-enc  {v_cost} XOR2  "
          f"({sum(len(c)-1 for c in core)} core + "
          f"{sum(w-1 for w in dec_w if w>=2)} decoder)")
    print(f"          known-optimal ratio {v_cost/d_cost:.4f}")

    # ---------------- negative control ----------------------------------
    rnd2 = random.Random(a.seed + 1)
    rows2 = []
    while len(rows2) < a.m:
        r = set(rnd2.sample(pool, a.wide))
        # reject if it lands close to an existing row: we want NO sparse
        # pairwise difference anywhere, so no row addition can pay.
        if all(len(r ^ s) >= a.wide for s in rows2):
            rows2.append(r)
    d2 = cost_direct(rows2)
    mindiff = min(len(rows2[i] ^ rows2[j])
                  for i in range(a.m) for j in range(i + 1, a.m))
    g2 = emit("bdnull", rows2, a.n, os.path.join(a.out, "bdnull.v"), [
        "bdnull -- boundary-decoder NEGATIVE control, generated by",
        "gen_bdec_fixture.py.  Same size, same density, same emitter as",
        "bdwin, but the rows are independent: the smallest pairwise row",
        f"difference is {mindiff}, so no single row addition can pay for",
        "itself and --bdec should decline.",
        f"Direct realisation: {d2} XOR2.",
    ])
    print(f"bdnull.v  m={a.m} n={a.n}  emitted {g2} gates")
    print(f"          direct  {d2} XOR2   min pairwise row difference {mindiff}")
    print(f"          (no row addition can reduce weight: any h_i = y_i + y_j")
    print(f"           has weight >= {mindiff} against y_i's {a.wide})")


if __name__ == "__main__":
    main()
