# ---------------------------------------------------------------------------
#  gen_spice_cells.py -- build the bundle's spice/ technology-cell library
#  Renesis: energy-aware reversible / adiabatic logic synthesis
#
#  v89.10, item 67. For every mapping-target family, synthesize the
#  canonical two-input gate (spice/and2.v) with the REAL flow and emit its
#  deck with the real --spice-gen path. Each deck is therefore an
#  authentic single-cell specimen of the family: its pass network, its
#  latch/keeper cell at the adjudicated topology, its power-clock
#  discipline, and the stub models with their replace-me warning. The
#  library is GENERATED, not hand-maintained: rerun this script after any
#  family change, and the release gate compares a regeneration against the
#  shipped folder so the two cannot drift.
#
#  Author:      Mitchell A. Thornton
#  Copyright:   (c) 2026 Clearpoint Research, LLC.  All rights reserved.
#  Modified:    2026-08-16  (Renesis v92.3)
#  Created:     Renesis v89.10 (earliest version token in file)
# ---------------------------------------------------------------------------
"""gen_spice_cells.py -- build the bundle's spice/ technology-cell library.

v89.10, item 67.  For every mapping-target family, synthesize the
canonical two-input gate (spice/and2.v) with the REAL flow and emit its
deck with the real --spice-gen path.  Each deck is therefore an authentic
single-cell specimen of the family: its pass network, its latch/keeper
cell at the adjudicated topology, its power-clock discipline, and the
stub models with their replace-me warning.  The library is GENERATED, not
hand-maintained: rerun this script after any family change, and the
release gate compares a regeneration against the shipped folder so the
two cannot drift.

    python3 scripts_adiabatic/gen_spice_cells.py           # write spice/
    python3 scripts_adiabatic/gen_spice_cells.py --check   # regenerate to a
                                                           # temp dir, diff
"""
import filecmp
import os
import shutil
import subprocess
import sys
import tempfile

BUNDLE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(BUNDLE)

FAMILIES = ["tgate", "tgate_sl6", "pfal", "ecrl", "cal", "pal", "spgal",
            "2lal", "s2lal"]

AND2 = """\
// and2.v -- the canonical cell-library specimen (ISCAS-style primitives)
module and2 (a, b, y);
  input a, b;
  output y;
  and g1 (y, a, b);
endmodule
"""

README = """\
# spice/ -- technology-cell SPICE decks

One deck per family, each the REAL tool's synthesis of the canonical
two-input gate (`and2.v`) emitted by `--spice-gen`: the family's dual-rail
pass network, its latch/keeper cell at the published topology (PAL per
Oklobdzija/Maksimovic/Lin 1997; SPGAL per Kumar/Thapliyal/Mohammad/
Perumalla 2017, billing adjudicated against the schematic), and its
power-clock discipline as trapezoidal PWL sources.  Inputs are driven
dual-rail and LEAD the power clock -- for SPGAL this is the five-interval
input drive confirmed by the family's author.

Run one:                 ngspice -b <family>_cell.sp
It writes <family>_cell_po.txt with the output rail waveforms.

THE MODELS ARE STUBS.  Every deck's header says so: level-1 MOSFETs stand
in so the deck runs anywhere; replace the .model cards with your
characterized PDK models before drawing any energy conclusion.  The
tool's own energy figures come from its calibrated C*V^2 model, not from
these decks; what a stub-model transient validates is FUNCTION and the
clocking discipline, and the shipped decks pass exactly that check
(scripts_adiabatic/check_spice_deck.py) on every family.

Full-circuit decks for any netlist:   renesis --spice-gen BASE <netlist>
This folder is generated by scripts_adiabatic/gen_spice_cells.py; the
release gate regenerates and compares it at every cut, so the folder
cannot drift from the tool.
"""


def build(outdir):
    os.makedirs(outdir, exist_ok=True)
    src = os.path.join(outdir, "and2.v")
    open(src, "w").write(AND2)
    open(os.path.join(outdir, "README.md"), "w").write(README)
    env = dict(os.environ, PYTHONHASHSEED="0")
    for fam in FAMILIES:
        base = os.path.join(outdir, "%s_cell" % fam)
        r = subprocess.run(
            [sys.executable, "scripts_adiabatic/renesis.py", "--tech", fam,
             "--spice-gen", base, "-q", src],
            capture_output=True, text=True, env=env)
        if r.returncode != 0:
            sys.exit("gen_spice_cells: %s failed:\n%s"
                     % (fam, (r.stdout + r.stderr)[-300:]))
        print("  %s_cell.sp" % fam)


def main():
    if "--check" in sys.argv:
        tmp = tempfile.mkdtemp(prefix="spicecheck")
        try:
            build(tmp)
            bad = []
            for f in sorted(os.listdir(tmp)):
                a, b = os.path.join(tmp, f), os.path.join("spice", f)
                if not os.path.exists(b):
                    bad.append(f + " (missing from spice/)")
                elif not filecmp.cmp(a, b, shallow=False):
                    bad.append(f)
            extra = [f for f in os.listdir("spice")
                     if f not in os.listdir(tmp)
                     and not f.endswith(("_po.txt",))]
            for f in extra:
                bad.append(f + " (extra in spice/)")
            if bad:
                print("gen_spice_cells --check: DRIFT: %s" % ", ".join(bad))
                sys.exit(1)
            print("gen_spice_cells --check: spice/ matches a fresh "
                  "regeneration (%d files)" % len(os.listdir(tmp)))
        finally:
            shutil.rmtree(tmp, ignore_errors=True)
    else:
        build("spice")
        print("spice/: %d files" % len(os.listdir("spice")))


if __name__ == "__main__":
    main()
